const GITHUB_ACCESS_TOKEN = process.env.GITHUB_ACCESS_TOKEN
const CIRCLE_PROJECT_USERNAME = process.env.CIRCLE_PROJECT_USERNAME
const CIRCLE_PROJECT_REPONAME = process.env.CIRCLE_PROJECT_REPONAME 
const CIRCLE_BUILD_NUM = process.env.CIRCLE_BUILD_NUM
const CIRCLE_ARTIFACTS = process.env.CIRCLE_ARTIFACTS 

console.log(GITHUB_ACCESS_TOKEN, CIRCLE_PROJECT_USERNAME, CIRCLE_PROJECT_REPONAME , CIRCLE_BUILD_NUM, CIRCLE_ARTIFACTS)

